image: node:14

stages:
    - build
    - test

build:
    stage: build
    script:
        - npm run test

test:
    stage: test
    script:
        - npm run test
        - curl -L https://get.datree.io/install-Linux.sh | /bin/bash
        - datree test kube/deployment.yaml
