language: node_js
node_js: '14'
script:
  - npm run build
  - npm run test
  - wget https://clipublic.s3.amazonaws.com/datree-cli_0.0.261-main_Linux_x86_64/datree && chmod +x datree
  - ./datree test kube/deployment.yaml
