version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm run test
      - run: curl -L https://get.datree.io/install-Linux.sh | /bin/bash
      - run: datree test kube/deployment.yaml

workflows:
  main:
    jobs:
      - build
      - test
