version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm run test
      - run: echo "Datree test kube/*"

workflows:
  welcome:
    jobs:
      - build
      - test
      
