version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm run test
      - run: wget https://clipublic.s3.amazonaws.com/datree-cli_0.0.261-main_Linux_x86_64/datree
      - run: chmod +x datree
      - run: ./datree test kube/deployment.yaml

workflows:
  main:
    jobs:
      - build
      - test
