annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 1.16.0
description: A NGINX Docker Community based Helm chart for Kubernetes
home: https://github.com/Mirantis/helm-charts
keywords:
  - nginx
  - http
  - web
  - www
  - reverse proxy
maintainers:
  - email: helmcharts@mirantis.com
    name: Mirantis
name: nginx
sources:
  - https://github.com/mirantis/helm-charts
  - http://www.nginx.org
type: application
version: 0.1.0